### ISSUE TITLE
Using the TZ env

### ISSUE THREAD

**Issue by delmicio** [pluie-org/docker-images#2]
Hi,

How can I change the system timezone? 

I've tried...
```
FROM pluie/alpine-apache-fpm

RUN cd /usr/local/bin \
    && curl -sS https://getcomposer.org/installer | php -- --filename=composer \
    && chmod +x composer \
    && rm -rf /var/cache/apk/*

ENV TZ=America/Argentina/Cordoba
```

But It remains `Europe/Paris`

**Comment by a-sansara** [comment]
Hi delmicio,

thks for your interest.
i will investigate and give you a response this night or tomorrow night

**Comment by a-sansara** [comment]
Hi delmicio,

i release version 1.6 (also latest), wich fix the TZ inheritance between pluie containers.
so TZ must be change now to your defined value, in system & php
